all: recurse-all
clean: recurse-clean
install: recurse-install

recurse-all:
	$(MAKE) -C src -f Makefile.win32 all

recurse-clean:
	$(MAKE) -C src -f Makefile.win32 clean

recurse-install:
	$(MAKE) -C src -f Makefile.win32 install
